// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"database/sql"
	"yalla_go/user"
)

// Injectors from wire.go:

func InitUserApi(db *sql.DB) user.API {
	repository := user.ProvideUserRepository(db)
	service := user.ProvideUserService(repository)
	api := user.ProvideUserAPI(service)
	return api
}
